services:
  postgres:
    image: postgres:16
    container_name: rabbitpark-postgres
    environment:
      POSTGRES_USER: rabbit
      POSTGRES_PASSWORD: rabbit123
      POSTGRES_DB: rabbitpark
    ports:
      - "5433:5432"
    volumes:
      - rabbitpark_data:/var/lib/postgresql/data

volumes:
  rabbitpark_data:
